<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="4" failed="1" total="8" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Learning TestNG" duration-ms="1256" started-at="2017-09-02T06:23:47Z" finished-at="2017-09-02T06:23:49Z">
    <groups>
    </groups>
    <test name="AnnotationAssertionTest" duration-ms="1186" started-at="2017-09-02T06:23:47Z" finished-at="2017-09-02T06:23:48Z">
      <class name="testng.learning.AnnotationAssertionTest">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:testng.learning.AnnotationAssertionTest@1b26f7b2]" name="beforeTest" is-config="true" duration-ms="4" started-at="2017-09-02T11:53:47Z" finished-at="2017-09-02T11:53:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="beforeMethodTest()[pri:0, instance:testng.learning.AnnotationAssertionTest@1b26f7b2]" name="beforeMethodTest" is-config="true" duration-ms="0" started-at="2017-09-02T11:53:48Z" finished-at="2017-09-02T11:53:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethodTest -->
        <test-method status="PASS" signature="positiveTest()[pri:0, instance:testng.learning.AnnotationAssertionTest@1b26f7b2]" name="positiveTest" duration-ms="8" started-at="2017-09-02T11:53:48Z" finished-at="2017-09-02T11:53:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- positiveTest -->
        <test-method status="PASS" signature="afterMethodTest()[pri:0, instance:testng.learning.AnnotationAssertionTest@1b26f7b2]" name="afterMethodTest" is-config="true" duration-ms="562" started-at="2017-09-02T11:53:48Z" finished-at="2017-09-02T11:53:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethodTest -->
        <test-method status="PASS" signature="afterMethodTest()[pri:0, instance:testng.learning.AnnotationAssertionTest@1b26f7b2]" name="afterMethodTest" is-config="true" duration-ms="108" started-at="2017-09-02T11:53:48Z" finished-at="2017-09-02T11:53:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethodTest -->
        <test-method status="PASS" signature="beforeMethodTest()[pri:0, instance:testng.learning.AnnotationAssertionTest@1b26f7b2]" name="beforeMethodTest" is-config="true" duration-ms="0" started-at="2017-09-02T11:53:48Z" finished-at="2017-09-02T11:53:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethodTest -->
        <test-method status="SKIP" signature="doLoginTest()[pri:0, instance:testng.learning.AnnotationAssertionTest@1b26f7b2]" name="doLoginTest" duration-ms="0" started-at="2017-09-02T11:53:48Z" finished-at="2017-09-02T11:53:48Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Do Not excute]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Do Not excute
	at testng.learning.AnnotationAssertionTest.doLoginTest(AnnotationAssertionTest.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.TestNG.privateMain(TestNG.java:1325)
	at org.testng.TestNG.main(TestNG.java:1294)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLoginTest -->
        <test-method status="PASS" signature="beforeMethodTest()[pri:0, instance:testng.learning.AnnotationAssertionTest@1b26f7b2]" name="beforeMethodTest" is-config="true" duration-ms="4" started-at="2017-09-02T11:53:48Z" finished-at="2017-09-02T11:53:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethodTest -->
        <test-method status="SKIP" signature="skipTest()[pri:0, instance:testng.learning.AnnotationAssertionTest@1b26f7b2]" name="skipTest" duration-ms="0" started-at="2017-09-02T11:53:48Z" finished-at="2017-09-02T11:53:48Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[THIS test cases is skipped]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: THIS test cases is skipped
	at testng.learning.AnnotationAssertionTest.skipTest(AnnotationAssertionTest.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.TestNG.privateMain(TestNG.java:1325)
	at org.testng.TestNG.main(TestNG.java:1294)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- skipTest -->
        <test-method status="PASS" signature="afterMethodTest()[pri:0, instance:testng.learning.AnnotationAssertionTest@1b26f7b2]" name="afterMethodTest" is-config="true" duration-ms="68" started-at="2017-09-02T11:53:48Z" finished-at="2017-09-02T11:53:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethodTest -->
        <test-method status="FAIL" signature="assertTest()[pri:0, instance:testng.learning.AnnotationAssertionTest@1b26f7b2]" name="assertTest" duration-ms="32" started-at="2017-09-02T11:53:48Z" finished-at="2017-09-02T11:53:48Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	expected [expected] but found [actual], 
	error message reported for failure	error message reported for failure]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [expected] but found [actual], 
	error message reported for failure	error message reported for failure
	at org.testng.Assert.fail(Assert.java:94)
	at testng.learning.AnnotationAssertionTest.assertTest(AnnotationAssertionTest.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.TestNG.privateMain(TestNG.java:1325)
	at org.testng.TestNG.main(TestNG.java:1294)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- assertTest -->
        <test-method status="PASS" signature="beforeMethodTest()[pri:0, instance:testng.learning.AnnotationAssertionTest@1b26f7b2]" name="beforeMethodTest" is-config="true" duration-ms="0" started-at="2017-09-02T11:53:48Z" finished-at="2017-09-02T11:53:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethodTest -->
        <test-method status="PASS" signature="afterMethodTest()[pri:0, instance:testng.learning.AnnotationAssertionTest@1b26f7b2]" name="afterMethodTest" is-config="true" duration-ms="68" started-at="2017-09-02T11:53:48Z" finished-at="2017-09-02T11:53:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethodTest -->
        <test-method status="SKIP" signature="changePasswordTest()[pri:0, instance:testng.learning.AnnotationAssertionTest@1b26f7b2]" name="changePasswordTest" duration-ms="0" started-at="2017-09-02T11:53:48Z" depends-on-methods="testng.learning.AnnotationAssertionTest.doLoginTest" finished-at="2017-09-02T11:53:48Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method AnnotationAssertionTest.changePasswordTest()[pri:0, instance:testng.learning.AnnotationAssertionTest@1b26f7b2] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method AnnotationAssertionTest.changePasswordTest()[pri:0, instance:testng.learning.AnnotationAssertionTest@1b26f7b2] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1040)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.TestNG.privateMain(TestNG.java:1325)
	at org.testng.TestNG.main(TestNG.java:1294)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- changePasswordTest -->
        <test-method status="SKIP" signature="logoutTest()[pri:0, instance:testng.learning.AnnotationAssertionTest@1b26f7b2]" name="logoutTest" duration-ms="0" started-at="2017-09-02T11:53:48Z" depends-on-methods="testng.learning.AnnotationAssertionTest.doLoginTest" finished-at="2017-09-02T11:53:48Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method AnnotationAssertionTest.logoutTest()[pri:0, instance:testng.learning.AnnotationAssertionTest@1b26f7b2] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method AnnotationAssertionTest.logoutTest()[pri:0, instance:testng.learning.AnnotationAssertionTest@1b26f7b2] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1040)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.TestNG.privateMain(TestNG.java:1325)
	at org.testng.TestNG.main(TestNG.java:1294)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutTest -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:testng.learning.AnnotationAssertionTest@1b26f7b2]" name="afterTest" is-config="true" duration-ms="0" started-at="2017-09-02T11:53:48Z" finished-at="2017-09-02T11:53:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- testng.learning.AnnotationAssertionTest -->
    </test> <!-- AnnotationAssertionTest -->
    <test name="ParameterizationTest" duration-ms="4" started-at="2017-09-02T06:23:49Z" finished-at="2017-09-02T06:23:49Z">
      <class name="testng.learning.AnnotationAssertionTest">
        <test-method status="PASS" signature="beforeSuiteTest()[pri:0, instance:testng.learning.AnnotationAssertionTest@1b26f7b2]" name="beforeSuiteTest" is-config="true" duration-ms="6" started-at="2017-09-02T11:53:47Z" finished-at="2017-09-02T11:53:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuiteTest -->
        <test-method status="PASS" signature="afterSuiteTest()[pri:0, instance:testng.learning.AnnotationAssertionTest@1b26f7b2]" name="afterSuiteTest" is-config="true" duration-ms="0" started-at="2017-09-02T11:53:49Z" finished-at="2017-09-02T11:53:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuiteTest -->
      </class> <!-- testng.learning.AnnotationAssertionTest -->
      <class name="testng.learning.ParameterizationTest">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:testng.learning.ParameterizationTest@c81cdd1]" name="beforeTest" is-config="true" duration-ms="0" started-at="2017-09-02T11:53:49Z" finished-at="2017-09-02T11:53:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:testng.learning.ParameterizationTest@c81cdd1]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2017-09-02T11:53:49Z" finished-at="2017-09-02T11:53:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:testng.learning.ParameterizationTest@c81cdd1]" name="afterMethod" is-config="true" duration-ms="1" started-at="2017-09-02T11:53:49Z" finished-at="2017-09-02T11:53:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="doLogin(java.lang.String, java.lang.String, int)[pri:0, instance:testng.learning.ParameterizationTest@c81cdd1]" name="doLogin" duration-ms="0" started-at="2017-09-02T11:53:49Z" data-provider="getData" finished-at="2017-09-02T11:53:49Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[raghav]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[kolhatkar]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[26101981]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method status="PASS" signature="doLogin(java.lang.String, java.lang.String, int)[pri:0, instance:testng.learning.ParameterizationTest@c81cdd1]" name="doLogin" duration-ms="0" started-at="2017-09-02T11:53:49Z" data-provider="getData" finished-at="2017-09-02T11:53:49Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[priyanka]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[bhide]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[22121985]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:testng.learning.ParameterizationTest@c81cdd1]" name="afterTest" is-config="true" duration-ms="0" started-at="2017-09-02T11:53:49Z" finished-at="2017-09-02T11:53:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:testng.learning.ParameterizationTest@c81cdd1]" name="afterMethod" is-config="true" duration-ms="0" started-at="2017-09-02T11:53:49Z" finished-at="2017-09-02T11:53:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:testng.learning.ParameterizationTest@c81cdd1]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2017-09-02T11:53:49Z" finished-at="2017-09-02T11:53:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
      </class> <!-- testng.learning.ParameterizationTest -->
    </test> <!-- ParameterizationTest -->
  </suite> <!-- Learning TestNG -->
</testng-results>
